### ISSUE TITLE
Chimney stabilization into 1.0.0

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#495]
List of things to do before preparing `1.0.0` (if needed turn these into separate issues):

 - [x] release [1.0.0-RC1](https://github.com/scalalandio/chimney/milestone/7)
   - [x] provide better nested paths to values in all `.withField*`/`.withSealedSubtype*` - followup to https://github.com/scalalandio/chimney/issues/358, unblocked in https://github.com/scalalandio/chimney/pull/490, https://github.com/scalalandio/chimney/pull/491, https://github.com/scalalandio/chimney/pull/492, done in https://github.com/scalalandio/chimney/pull/493
     - [x] with #499
     - [x] and https://github.com/scalalandio/chimney/discussions/498 (#512)
   - [x] deprecate `.withCoproductInstance` in favor of `.withSealedSubtypeComputed` + `.withEnumCaseComputed` (alias) - #500
   - [x] provide interface for custom optional types and collections
     - [x] integrate it with better nested paths
     - [x] use it to re-implement chimney-java-collections (#510)
     - [x] use it to implement chimney-cats support for `NonEmpty*`/`Chain` (#421, fixed in #511)
   - [x] verify that mutable collections are supported
   - [x] ~verify that `IArray` on Scala 3 is supported~ there is some issue, I'll talk to Scala 3 people about it
   - [x] documentation
     - [x] differences between `.withSealedSubtype[Sub](...)` and `withFieldComputed(_.matching[Sub], ...)`
     - [x] limitations of `.withFieldRenamed` on left path (only fieldnames)
     - [x] limitations of option/either support (cannot use `.matching`)
     - [x] ~Scala 3 bugs - https://github.com/scalalandio/chimney/issues/479, https://github.com/scalalandio/chimney/issues/482, https://github.com/scalalandio/chimney/issues/484~ - it seems that if these bugs will be fixed it's not going to be anytime before the release of RC, we might add information about the bugs/workarounds later when they are known
     - [x] Scaladocs - make scaladocs compile without disabling `-Xfatal-errors` - https://github.com/scalalandio/chimney/pull/494
     - [x] ~check documentation (.md) formatting with Scala CLI + scalafmt~ - unfortunately it cannot work OOTB for us currently 
     - [x] format scaladoc with scalafmt (change `docstrings.wrap = no` to `yes`)
     - [x] add light/dark theme toggle to documentation - #503
     - [x] document gotchas and weird workarounds in code (Scala 2 enum workarounds, inconsistency with `Matching` for normal ADT, Options and Eithers)
     - [x] document internal structures, why they exist etc
 - [x] add RC versions to MiMa
 - [x] ~change `versionScheme` to `:= Some("semver")`~ - actially `early-semver` does not mean that the library is immature but that it's 0.x versions [are bincompatible within `x`](https://www.scala-sbt.org/1.x/docs/Publishing.html#Version+scheme), we do not need to change it

This is more of my private todo wishlist than any official promise. Content subject to change, no ETA.
